### ISSUE TITLE
RPM CLI Install Failing Due to Signature Verification Failure

### ISSUE THREAD

**Issue by Zulcon** [jotta/jotta-cli-issues#209]
Followed the steps listed here: (https://docs.jottacloud.com/en/articles/1436860-jottacloud-cli-for-linux-rpm-packages)

`Running transaction
Transaction failed: Signature verification failed.
OpenPGP check for package "jotta-cli-0.17.132497-2.x86_64" (/var/cache/libdnf5/jotta-cli-cc725804aa790275/packages/jotta-cli-0.17.132497-2.x86_64.rpm) from repo "jotta-cli" has failed: Problem occurred when opening the package.
`

I am unable to install on Fedora 42 KDE edition. Have attempted to all steps on that page to resolve, but it just appears the pgp key has expired and will need to be updated, which looks like the same thing occurred for the .deb key as well based on the report here: https://github.com/jotta/jotta-cli-issues/issues/208

Also the RPM guide may need to be updated as well as it seems some of the troubleshooting steps listed there no longer work.

`> sudo rpm -q gpg-pubkey --qf "%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n" | grep "Jottacloud" | awk '{ print $1}' | xargs -r rpm -e sudo rpm --import https://repo.jotta.cloud/public.gpg 
rpmkeys: --erase: unknown option
`

**Comment by Kimbsen** [comment]
We published a new version now. It should fix that issue.

**Comment by dotknewt** [comment]
The suggested "update keys" command is not working (Fedora 43)
`rpmkeys: only one major mode may be specified`

It's not possible to import the key as its not an armored public key which seems to be a requirement. Maybe this was introduced in Fedora 43?

**Comment by Kimbsen** [comment]
yeah, sorry the documentation was not correct. It has been updated and should work with fedora:43 now

**Comment by dotknewt** [comment]
> yeah, sorry the documentation was not correct. It has been updated and should work with fedora:43 now

Just tested, and it's working fine now, thanks!

**Comment by dotknewt** [comment]
Updates using "Gnome Software" is still throwing errors though. I believe changing the repo-file value for `gpgkey` fixes the issue, as the install instructions still refer to the gpg key, not the asc key.

Import the new asc key: `sudo rpm --import https://repo.jotta.cloud/public.asc`

Backup the existing repo-file `cp /etc/yum.repos.d/JottaCLI.repo $HOME/Downloads/JottaCLI.repo.bak`

Create new repo-file:
`echo -e "[jotta-cli]\nname=Jottacloud CLI\nbaseurl=https://repo.jotta.cloud/redhat\nenabled=1\nautorefresh=1\ntype=rpm\ngpgcheck=1\ngpgkey=https://repo.jotta.cloud/public.asc" | sudo tee /etc/yum.repos.d/JottaCLI.repo`

**Comment by Zulcon** [comment]
> Updates using "Gnome Software" is still throwing errors though. I believe changing the repo-file value for `gpgkey` fixes the issue, as the install instructions still refer to the gpg key, not the asc key.
> 
> Import the new asc key: `sudo rpm --import https://repo.jotta.cloud/public.asc`
> 
> Backup the existing repo-file `cp /etc/yum.repos.d/JottaCLI.repo $HOME/Downloads/JottaCLI.repo.bak`
> 
> Create new repo-file: `echo -e "[jotta-cli]\nname=Jottacloud CLI\nbaseurl=https://repo.jotta.cloud/redhat\nenabled=1\nautorefresh=1\ntype=rpm\ngpgcheck=1\ngpgkey=https://repo.jotta.cloud/public.asc" | sudo tee /etc/yum.repos.d/JottaCLI.repo`

If anyone else finds this when trying to install on Bazzite or other atomic/immutable distributions, these steps above will work just fine, but just some tweaks.

Run first to get the correct key:
`sudo curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-jotta.asc https://repo.jotta.cloud/public.asc`

Then add it to your repo file:
```
sudo tee /etc/yum.repos.d/jotta-cli.repo <<EOF[jotta-cli]
name=Jottacloud CLI
baseurl=https://repo.jotta.cloud/redhat
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-jotta.asc
EOF
```

Then running `rpm-ostree install jotta-cli` should work just fine and let you set up like normal.

**Comment by al12gamer** [comment]
I think this is still an issue. Updated today both manually and attempted using topgrade on Fedora 44 and received this:
```
Importing OpenPGP key 0x947F9F0F:
 UserID     : "Jottacloud Packaging Team <packaging@jottacloud.com>"
 Fingerprint: E2CBEED2DECB21BF686AB4B37DEFBCE9947F9F0F
 From       : https://repo.jotta.us/public.gpg
The key was successfully imported.
Transaction failed: Signature verification failed.
OpenPGP check for package "jotta-cli-0.17.176206-1.x86_64" (/var/cache/libdnf5/jotta-cli-fd8748e081d8a669/packages/jotta-cli-0.17.176206-1.x86_64.rpm) from repo "jotta-cli" has failed: Import of the key didn't help, wrong key?
System update failed: 
   0: Command failed: `/usr/bin/sudo /usr/bin/dnf upgrade -y`
   1: `/usr/bin/sudo` failed: exit status: 1

```

**Comment by sonocculture** [comment]
I can confirm that this is still an issue on Fedora 44. 

```Importing OpenPGP key 0x947F9F0F:
 UserID     : "Jottacloud Packaging Team <packaging@jottacloud.com>"
 Fingerprint: E2CBEED2DECB21BF686AB4B37DEFBCE9947F9F0F
 From       : https://repo.jotta.us/RPM-GPG-KEY-jotta-cli
Is this ok [y/N]: y
The key was successfully imported.
Transaction failed: Signature verification failed.
OpenPGP check for package "jotta-cli-0.17.176206-1.x86_64" (/var/cache/libdnf5/jotta-cli-fd8748e081d8a669/packages/jotta-cli-0.17.176206-1.x86_64.rpm) from repo "jotta-cli" has failed: Import of the key didn't help, wrong key?```

**Comment by ehrktia** [comment]
work around : 

1. uninstall existing installation of the cli  
2. check if your existing repo file exists in `/etc/yum.d/repos` folder, if not create them using installation guide wiki  
3. update the gpg key using https://docs.jottacloud.com/en/articles/1436860-jottacloud-cli-for-linux-rpm-packages  
4.  install using yum `sudo yum install jotta-cli`

**Comment by al12gamer** [comment]
yum is depreciated
Anyway, I removed the package, updated my system (it was holding it back) and then tried installing jotta-cli again:
```
sudo dnf install jotta-cli
Place your right index finger on the fingerprint reader
Updating and loading repositories:
Repositories loaded.
Package                                                              Arch            Version                                                              Repository                                   Size
Installing:
 jotta-cli                                                           x86_64          0:0.17.176206-1                                                      jotta-cli                                51.6 MiB

Transaction Summary:
 Installing:         1 package

Total size of inbound packages is 18 MiB. Need to download 18 MiB.
After this operation, 52 MiB extra will be used (install 52 MiB, remove 0 B).
Is this ok [y/N]: y
[1/1] jotta-cli-0:0.17.176206-1.x86_64                                                                                                                             100% | 785.9 KiB/s |  18.2 MiB |  00m24s
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1/1] Total                                                                                                                                                        100% | 785.8 KiB/s |  18.2 MiB |  00m24s
[2/2] https://repo.jotta.us/public.gpg                                                                                                        ???% [<=>               ] |   0.0   B/s |   0.0   B |  00m00s
[2/2] https://repo.jotta.us/public.gpg                                                                                                        ???% [<=>               ] |   0.0   B/s |   0.0   B |  00m00s
[2/2] https://repo.jotta.us/public.gpg                                                                                                        ???% [<=>               ] |   0.0   B/s |   0.0   B |  00m00s
[2/2] https://repo.jotta.us/public.gpg                                                                                                        ???% [ <=>              ] |   0.0   B/s |   0.0   B |  00m01s
[2/2] https://repo.jotta.us/public.gpg                                                                                                        ???% [ <=>              ] |   0.0   B/s |   0.0   B |  00m01s
[2/2] https://repo.jotta.us/public.gpg                                                                                                        100% [==================] |   3.2 KiB/s |   3.7 KiB |  00m00s
[2/2] https://repo.jotta.us/public.gpg                                                                                                                             100% |   3.2 KiB/s |   3.7 KiB |  00m01s
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[2/2] Total                                                                                                                                                        100% | 785.8 KiB/s |  18.2 MiB |  00m24s
Importing OpenPGP key 0x947F9F0F:
 UserID     : "Jottacloud Packaging Team <packaging@jottacloud.com>"
 Fingerprint: E2CBEED2DECB21BF686AB4B37DEFBCE9947F9F0F
 From       : https://repo.jotta.us/public.gpg
Is this ok [y/N]: y
The key was successfully imported.
Transaction failed: Signature verification failed.
OpenPGP check for package "jotta-cli-0.17.176206-1.x86_64" (/var/cache/libdnf5/jotta-cli-fd8748e081d8a669/packages/jotta-cli-0.17.176206-1.x86_64.rpm) from repo "jotta-cli" has failed: Import of the key didn't help, wrong key?

```

**Comment by sonocculture** [comment]
As a workaround until this is fixed, you can exclude jotta-cli from your package updates with the `--exclude` option:
```sudo dnf update --refresh --exclude=jotta-cli```
